version: "3.7"
services:
  
  # browse to: https://localhost:9443/ibmmq/console
  ibmcom_mq_sistemaa:
    image: ibmcom/mq
    ports:
      - "1414:1414"
      - "9443:9443"    
    container_name: ibmcom_mq_sistemaa
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    volumes: 
      - .files\qm1data:/mnt/mqm
    stdin_open: true
    tty: true
    restart: always
    

    
    
    
    
  

